### ISSUE TITLE
[Feature Request] Cycling only tools

### ISSUE THREAD

**Issue by Rad586** [KrLite/Tap-Tab#4]
With some mods with backpack sorting feature, cycling through inventory is sometimes not accurate enough. I think it would be more efficient to have the "cycling only tools" feature.

**Comment by KrLite** [comment]
After considering, I added 'Cycling Only Main Hand Slot' function in the end. I think that could be a proper workaround. Something like 'Cycling Only Tools' is quite vague and tricky to implement, so I won't do that in the near future.

I hope that 'Cycling Only Main Hand Slot' can solve the problem of not being accurate enough in some extend.
