### ISSUE TITLE
Forced out of server on tapping tab

### ISSUE THREAD

**Issue by ChromaPIE** [KrLite/Tap-Tab#5]
Using mod version 1.1.0, game version 1.19.2 Fabric with Fabric Loader 0.14.17 (reproduced on 0.14.15 too). Same Fabric & mod version on server.

Related log on server console: https://mclo.gs/wJTnBw3

**Comment by ChromaPIE** [comment]
@KrLite yo would you please check this out real quick

**Comment by KrLite** [comment]
Sorry for that I didn't appear, I'm here to fix this now. Gonna do it quick

**Comment by ChromaPIE** [comment]
Yea but you told me that the bugged version was literally left out of maintenance and I spent one whole month waiting for a fix that's not even for the version I play right? Aight.

**Comment by ChromaPIE** [comment]
if i know the fix wont be for 1.19.2 i wont even open this issue. im not here to help the mod get better i want my issue fixed.

anyway im using HotbarCycle. thanks for doing nothing good to me.
